In [2]:
import numpy as np
import pandas as pd

data = np.arange(30,60).reshape(5,6)
print(data)

[[30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


In [3]:
data1 = np.linspace(20,10,4)
print(data1)

[20.         16.66666667 13.33333333 10.        ]


In [4]:
ran = np.random.randint(10)
print(ran)


6


In [5]:
# Dataframe : is the composition of series
data_frame = pd.DataFrame(data,index=['Row1','Row2','Row3','Row4','Row5'],columns=['Name','Address','my','gre','mat','net'])
# print(data_frame)
# get all columns
# data_frame.columns
# df.shape shows how many rows and columns
# data_frame.shape
# get df.head first 5 rows
# data_frame.head()
# fget df.tail last 5 rows
# data_frame.tail(3)
# df.sample
# data_frame.sample()
# df.info to get all information of data
# data_frame.info()
# df.describe descriptive summary of columns with numeric datatype
# data_frame.describe()

In [6]:
# Generating sample Google Play Store data
data4 = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [7]:
# df=pd.DataFrame(data4)
# when to get multiple columns from 2d array
# df[['App','Category','Rating']]
# df.shape
# print(pd.core.series.Series)
# df.info()
# df.head()
# df.tail()
# df.sample()
# df.describe()
# df['Price'].unique()
# df['Price'] =df['Price'].replace('Free','0')
# df['Price']

In [29]:
df = pd.read_csv('./sample_data/googleplaystore.csv')
# df.head()
# df.tail()
# your primary duty to identify that columns are in correct format
# df.info()
# har specific columns ki misssing value bata daye ga
# df.isnull().sum()
# string filll with mode most repeated value
# mean aur median stdeviation and variance for numeric columns
# now price columns are in object we have to make it numberic
# df['Price'].unique()
# give all unique values you will identify the what values are not proper
# repalce 'Everyone' with zero and change datatype of columns
df['Price'] = df['Price'].replace('Everyone','0')
df['Price'] =  df['Price'].str.replace('$','').astype(float)
df['Price'].unique()
# to check datatype
# df.Price.dtype
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10841 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object 
 4   Size            10841 non-null  object 
 5   Installs        10841 non-null  object 
 6   Type            10840 non-null  object 
 7   Price           10841 non-null  float64
 8   Content Rating  10840 non-null  object 
 9   Genres          10841 non-null  object 
 10  Last Updated    10841 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(2), object(11)
memory usage: 1.1+ MB


In [54]:

# convert size colum to flaot
# df['Size'] = df['Size'].str.replace('M','').replace('k','').astype(float)
# df['Size'] = df['Size'].replace('Varies with device','0')
# df['Size'] = df['Size'].str.replace('k','')
df['Size'] = df['Size'].str.replace('+','')
df['Size'] = df['Size'].str.replace(',','')
df['Size']=df['Size'].astype(float)
df['Size'].unique()
# to remove duplicates
df.drop_duplicates(subset='App')
# df.shape gives roes and columns
df.shape()

AttributeError: Can only use .str accessor with string values!

In [58]:
# to remove duplicates
df = df.drop_duplicates(subset='App')
# df.shape gives roes and columns
# df.shape
df

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews  Size     Installs  Type  Price Content Rating  \
0         4.1     159  19.0      10,000+  Free    0.0       Everyone   
1         3.9     967  14.0     500,000+  Free    0.0       Everyone   
2         4.7   87510   8.7   5,000,000+  Free    0.0       Everyone   
3         4.5  215644  25.0  50,000,000+  Free    0.0           Teen   
4         4.3     967   2.8     100,000+  Free    0.0       Everyone   
...       ...     ...   ...          ...   ...    ...            ...   
10836     4.5      38  53.0       5,000+  Free    0.0       Everyone   
10837     5.0       4   3.6         100+  Free    0.0       Everyone   
10838     NaN       3   9.5       1,000+  Free    0.0       Everyone   
10839     4.5     114   0.0       1,000+  Free    0.0     Mature 17+   
10840     4.5  398307  19.0  10,000,000+  Free    0.0       Everyone   

                          Genres      Last Updated         Current Ver  \
0                   Art & Design   January 7, 2018               1.0.0   
1      Art & Design;Pretend Play  January 15, 2018               2.0.0   
2                   Art & Design    August 1, 2018               1.2.4   
3                   Art & Design      June 8, 2018  Varies with device   
4        Art & Design;Creativity     June 20, 2018                 1.1   
...                          ...               ...                 ...   
10836                  Education     July 25, 2017                1.48   
10837                  Education      July 6, 2018                   1   
10838                    Medical  January 20, 2017                   1   
10839          Books & Reference  January 19, 2015  Varies with device   
10840                  Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
0            4.0.3 and up  
1            4.0.3 and up  
2            4.0.3 and up  
3              4.2 and up  
4              4.4 and up  
...                   ...  
10836          4.1 and up  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device  

[9660 rows x 13 columns]

In [63]:
# rating columns
df['Rating'].unique()
# how i dentify mean aur median calculae both if differnce bohat ziyada ho to mena se fill karaye gaye
df['Rating'].mean()
df['Rating'].median()

4.3

In [64]:
df['Rating'] = df['Rating'].fillna(df['Rating'].mean())
df['Rating'].unique()

array([ 4.1       ,  3.9       ,  4.7       ,  4.5       ,  4.3       ,
        4.4       ,  3.8       ,  4.2       ,  4.6       ,  3.2       ,
        4.        ,  4.17505185,  4.8       ,  4.9       ,  3.6       ,
        3.7       ,  3.3       ,  3.4       ,  3.5       ,  3.1       ,
        5.        ,  2.6       ,  3.        ,  1.9       ,  2.5       ,
        2.8       ,  2.7       ,  1.        ,  2.9       ,  2.3       ,
        2.2       ,  1.7       ,  2.        ,  1.8       ,  2.4       ,
        1.6       ,  2.1       ,  1.4       ,  1.5       ,  1.2       ,
       19.        ])

In [68]:
df['Reviews'] = df['Reviews'].str.replace('M','').astype(float)
df['Reviews'].unique()

array([1.59000e+02, 9.67000e+02, 8.75100e+04, ..., 6.03000e+02,
       1.19500e+03, 3.98307e+05])

In [71]:
# df.head()
# now for numerilization of columns Reviews
# humesha data normalize hota hai between 0 and 1
# formula currentvalue - minvalue/maxvalue - minvalue
df['Reviews'] = (df['Reviews'] - df['Reviews'].min())/(df['Reviews'].max() - df['Reviews'].min())
df['Popularity'] = df['Reviews'] * df['Rating']
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

    Reviews  Size     Installs  Type  Price Content Rating  \
0  0.000002  19.0      10,000+  Free    0.0       Everyone   
1  0.000012  14.0     500,000+  Free    0.0       Everyone   
2  0.001120   8.7   5,000,000+  Free    0.0       Everyone   
3  0.002759  25.0  50,000,000+  Free    0.0           Teen   
4  0.000012   2.8     100,000+  Free    0.0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  Popularity  
0  4.0.3 and up    0.000008  
1  4.0.3 and up    0.000048  
2  4.0.3 and up    0.005262  
3    4.2 and up    0.012416  
4    4.4 and up    0.000053

In [74]:
# to find which app is popular the most
df.sort_values(by='Popularity',ascending=False).head(3)
# df.head()

App       Category  Rating   Reviews  Size  \
2544            Facebook         SOCIAL     4.1  1.000000   0.0   
336   WhatsApp Messenger  COMMUNICATION     4.4  0.884350   0.0   
2545           Instagram         SOCIAL     4.5  0.851826   0.0   

            Installs  Type  Price Content Rating         Genres  \
2544  1,000,000,000+  Free    0.0           Teen         Social   
336   1,000,000,000+  Free    0.0       Everyone  Communication   
2545  1,000,000,000+  Free    0.0           Teen         Social   

        Last Updated         Current Ver         Android Ver  Popularity  
2544  August 3, 2018  Varies with device  Varies with device    4.100000  
336   August 3, 2018  Varies with device  Varies with device    3.891141  
2545   July 31, 2018  Varies with device  Varies with device    3.833219